### ISSUE TITLE
Blocks with FALL behavior are duplicated several times with the Repose mod

### ISSUE THREAD

**Issue by floral-qua-floral** [fredtargaryen/Fragile-Glass#19]
If the [Repose](https://www.curseforge.com/minecraft/mc-mods/Repose) mod is installed alongside FGTI, any block with the Fall behavior will spawn several FallingBlock entities instead of just one. They can land separately or all in the same location, which causes most to drop as items - either way, this duplicates the block several times over, which isn't good news.

**Comment by fredtargaryen** [comment]
Hi,
Thanks for reporting this; looking into it now.

**Comment by fredtargaryen** [comment]
I think [this jar](https://www.curseforge.com/minecraft/mc-mods/fragile-glass-and-thin-ice/files/2782276) should solve it; please could you confirm? Best to confirm on a new world as this version is halfway through a new feature.

**Comment by floral-qua-floral** [comment]
Yes, this does seem to fix the issue. I'm not noticing any duplication occurring anymore. Looking forward to this feature getting into a stable release so that I can have this mod and Repose together.

**Comment by floral-qua-floral** [comment]
whoops, didn't mean to close the issue... Sorry about that, it's your call whether this should be closed now or once the patch is added to a stable release.

**Comment by fredtargaryen** [comment]
Thanks for confirming! I think this should be closed as of https://github.com/fredtargaryen/Fragile-Glass/commit/bfa99d9eb8e0fc021f8c88c3da281dc75b989f74. Tile entities don't all fall perfectly but I believe this is a vanilla problem.
