### ISSUE TITLE
2.0.5 Alpha version named incorrectly or is wrong file

### ISSUE THREAD

**Issue by DWX12** [fredtargaryen/Fragile-Glass#20]
The 2.0.5 alpha version that is currently up is named 2.0.4, which is either just the wrong name or it's the wrong file that was uploaded.

**Comment by fredtargaryen** [comment]
Hi,
That version will only be up while I wait for confirmation that a different issue has been resolved. I don't recommend downloading it.

**Comment by fredtargaryen** [comment]
Closing this now as I'm about to take that one down and upload a new version.
