### ISSUE TITLE
[1.12.2] Ice patch generation not working

### ISSUE THREAD

**Issue by CalaMariGold** [fredtargaryen/Fragile-Glass#25]
We talked about this some time ago, figured I would make a GitHub issue for it.

Full context:
https://www.curseforge.com/minecraft/mc-mods/fragile-glass-and-thin-ice?comment=76

**Comment by fredtargaryen** [comment]
Hi, sorry I wasn't able to deal with this issue. My policy is to only maintain the mod for the current and previous main versions of Forge. I'll see if I can do something after I port Fragile Glass to 1.16.3, but I'm not promising anything.

**Comment by CalaMariGold** [comment]
All good! Just figured a main feature of the mod should at least function for all versions (well, I assume that's what most mod developers would like). If you do fix this issue, I'll definitely include it in Rebirth of the Night, bringing this genius mod to a much larger audience :)

**Comment by fredtargaryen** [comment]
Good news!

Figured out what's going on and now it works fine in vanilla and with the mods you mentioned. I definitely don't feel like a genius now I know the cause, but there you go. [Here's version 2.1.2](https://www.curseforge.com/minecraft/mc-mods/fragile-glass-and-thin-ice/files/3104736)

I think this is done but I'll leave the issue up a bit longer or until you confirm it's working, just in case.

**Comment by CalaMariGold** [comment]
Ice patch generation works. Stone generation works although isn't ideal with Underground biomes since it's just a single block and doesn't match the surrounding stone. We'll be using another way for weak stone so it's no big deal, although other people may want it.

**Comment by fredtargaryen** [comment]
That's a good point. What's the other way you mentioned? Thank you for confirming!

**Comment by CalaMariGold** [comment]
A block gravity mod for 1.12.
